/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

public class Problem2 {

	public static void main(String[] args) {
		int n=4000000;
		int a=0;
		int b=1;
		int sum=0;
		int c=0;
		for(;c<n;c++)
		{
			c=a+b;
			a=b;
			b=c;
			if(c%2==0) {
				sum=sum+c;
			}
		}
System.out.println("Sum="+sum);
	}

}
//Output=4613732
